// Single source of truth for the species list and per-species breed options on
// the frontend. The species *values* here must stay in lockstep with the
// `Pet.species` / `PetInput.species` enum in lib/api-spec/openapi.yaml (and
// the orval-generated types derived from it) — this file isn't generated, so
// a change on one side needs the matching edit on the other.

export const SPECIES_VALUES = [
  'dog',
  'cat',
  'rabbit',
  'bird',
  'fish',
  'hamster',
  'pig',
  'horse',
  'reptile',
  'ferret',
  'other',
] as const;

export type Species = (typeof SPECIES_VALUES)[number];

export const SPECIES_OPTIONS: readonly { value: Species; label: string }[] = [
  { value: 'dog', label: 'Dog' },
  { value: 'cat', label: 'Cat' },
  { value: 'rabbit', label: 'Rabbit' },
  { value: 'bird', label: 'Bird' },
  { value: 'fish', label: 'Fish' },
  { value: 'hamster', label: 'Hamster' },
  { value: 'pig', label: 'Pig' },
  { value: 'horse', label: 'Horse' },
  { value: 'reptile', label: 'Reptile' },
  { value: 'ferret', label: 'Ferret' },
  { value: 'other', label: 'Other' },
];

type BreedOption = { value: string; label: string };

const options = (breeds: readonly string[]): BreedOption[] => breeds.map((breed) => ({ value: breed, label: breed }));

export const BREEDS_BY_SPECIES: Record<Species, readonly BreedOption[]> = {
  dog: options([
    'Mixed breed',
    'Labrador Retriever',
    'Golden Retriever',
    'German Shepherd',
    'French Bulldog',
    'Bulldog',
    'Poodle',
    'Beagle',
    'Rottweiler',
    'Dachshund',
    'Yorkshire Terrier',
    'Boxer',
    'Australian Shepherd',
    'Siberian Husky',
    'Great Dane',
    'Cavalier King Charles Spaniel',
    'Doberman Pinscher',
    'Cane Corso',
    'Miniature Schnauzer',
    'Shih Tzu',
    'Boston Terrier',
    'Pomeranian',
    'Havanese',
    'Bernese Mountain Dog',
    'Chihuahua',
    'Pug',
    'Cocker Spaniel',
    'Border Collie',
    'Maltese',
    'Akita',
    'Newfoundland',
    'Basset Hound',
    'Rhodesian Ridgeback',
    'Weimaraner',
    'Vizsla',
    'Australian Cattle Dog',
    'Jack Russell Terrier',
    'West Highland White Terrier',
    'Bichon Frise',
    'Mastiff',
    'Saint Bernard',
    'English Springer Spaniel',
    'Irish Setter',
    'Whippet',
    'Greyhound',
    'Papillon',
    'Shetland Sheepdog',
    'Collie',
    'Staffordshire Bull Terrier',
    'Other / Not listed',
  ]),
  cat: options([
    'Domestic Shorthair',
    'Domestic Longhair',
    'Domestic Medium Hair',
    'Mixed breed',
    'Abyssinian',
    'American Shorthair',
    'Bengal',
    'Birman',
    'British Shorthair',
    'Burmese',
    'Burmilla',
    'Chartreux',
    'Cornish Rex',
    'Devon Rex',
    'Egyptian Mau',
    'Himalayan',
    'Maine Coon',
    'Manx',
    'Norwegian Forest Cat',
    'Ocicat',
    'Oriental Shorthair',
    'Persian',
    'Ragdoll',
    'Russian Blue',
    'Savannah',
    'Scottish Fold',
    'Siamese',
    'Siberian',
    'Singapura',
    'Snowshoe',
    'Somali',
    'Sphynx',
    'Tonkinese',
    'Toyger',
    'Turkish Angora',
    'Other / Not listed',
  ]),
  rabbit: options([
    'Mixed breed',
    'American',
    'Angora',
    'Belgian Hare',
    'Beveren',
    'Britannia Petite',
    'Californian',
    'Champagne d’Argent',
    'Checkered Giant',
    'Chinchilla',
    'Dutch',
    'Dwarf Hotot',
    'English Lop',
    'English Spot',
    'Flemish Giant',
    'Holland Lop',
    'Jersey Wooly',
    'Lionhead',
    'Mini Lop',
    'Mini Rex',
    'Netherland Dwarf',
    'New Zealand',
    'Polish',
    'Rex',
    'Satin',
    'Silver Fox',
    'Other / Not listed',
  ]),
  bird: options([
    'Budgerigar / Parakeet',
    'Cockatiel',
    'African Grey Parrot',
    'Amazon Parrot',
    'Blue-and-Gold Macaw',
    'Scarlet Macaw',
    'Cockatoo',
    'Conure',
    'Eclectus Parrot',
    'Lovebird',
    'Finch',
    'Canary',
    'Dove',
    'Pigeon',
    'Quaker Parrot',
    'Parrotlet',
    'Mynah',
    'Chicken',
    'Duck',
    'Goose',
    'Other / Not listed',
  ]),
  fish: options([
    'Betta',
    'Goldfish',
    'Guppy',
    'Neon Tetra',
    'Angelfish',
    'Molly',
    'Platy',
    'Swordtail',
    'Koi',
    'Cichlid',
    'Corydoras Catfish',
    'Discus',
    'Oscar',
    'Zebra Danio',
    'Pleco (Plecostomus)',
    'Tiger Barb',
    'Rainbowfish',
    'Gourami',
    'Clown Loach',
    'Killifish',
    'Other / Not listed',
  ]),
  hamster: options([
    'Syrian (Golden) Hamster',
    "Campbell's Dwarf Russian Hamster",
    'Winter White Russian Dwarf Hamster',
    'Roborovski Dwarf Hamster',
    'Chinese Hamster',
    'Other / Not listed',
  ]),
  pig: options([
    'Mixed breed',
    'Yorkshire',
    'Berkshire',
    'Duroc',
    'Hampshire',
    'Landrace',
    'Chester White',
    'Poland China',
    'Spot',
    'Tamworth',
    'Large Black',
    'Gloucestershire Old Spot',
    'Hereford',
    'Vietnamese Pot-Bellied',
    'Kunekune',
    'American Mini Pig',
    'Juliana Pig',
    'Other / Not listed',
  ]),
  horse: options([
    'Mixed breed',
    'Arabian',
    'Thoroughbred',
    'Quarter Horse',
    'Appaloosa',
    'Paint Horse',
    'Clydesdale',
    'Friesian',
    'Morgan',
    'Andalusian',
    'Mustang',
    'Shetland Pony',
    'Welsh Pony',
    'Tennessee Walking Horse',
    'Standardbred',
    'Percheron',
    'Belgian Draft',
    'Gypsy Vanner',
    'Icelandic Horse',
    'Hanoverian',
    'Lipizzaner',
    'Miniature Horse',
    'Other / Not listed',
  ]),
  reptile: options([
    'Bearded Dragon',
    'Leopard Gecko',
    'Crested Gecko',
    'Ball Python',
    'Corn Snake',
    'King Snake',
    'Boa Constrictor',
    'Blue-Tongued Skink',
    'Green Iguana',
    'Veiled Chameleon',
    'Red-Eared Slider (Turtle)',
    'Box Turtle',
    'Russian Tortoise',
    'Sulcata Tortoise',
    'Monitor Lizard',
    'Chinese Water Dragon',
    'Other / Not listed',
  ]),
  ferret: options([
    'Sable',
    'Black Sable',
    'Albino',
    'Black-Eyed White',
    'Chocolate',
    'Cinnamon',
    'Champagne',
    'Silver',
    'Panda',
    'Blaze',
    'Point (Siamese)',
    'Other / Not listed',
  ]),
  other: options(['Mixed breed', 'Unknown', 'Other / Not listed']),
};
